apiVersion: apps/v1
kind: Deployment
metadata:
  name: msctime-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: msctime
        image: feydrauth/msctime:latest
        ports:
        - containerPort: 8000
